version: '3.5'

services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony_base
        volumes:
            # if you will use percona:5.7 and have some permission issue sudo chown 999:999 ./.docker/.mysql-data
            - ./.docker/.mysql-data:/var/lib/mysql:rw,delegated
        ports:
            - 3308:3306
        networks:
            - internal

    php:
        build:
            context: .
            target: symfony_php
        depends_on:
            - mysql
        environment:
            # Add "client_host", can be your local IP by default try to use docker0 IP
            # For more config see: https://blog.denisbondar.com/post/phpstorm_docker_xdebug
            XDEBUG_CONFIG: "client_host=192.168.100.1"
            PHP_IDE_CONFIG: "serverName=Docker"
            APP_ENV: dev
            APP_DEBUG: 1
            DATABASE_URL: mysql://root:root@mysql/symfony_base
            PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
        volumes:
            - .:/srv:rw,cached
            - ./var:/srv/var:rw
            - ./public:/srv/public:rw,delegated
        networks:
            - internal

    nginx:
        build:
            context: .
            target: symfony_nginx
        depends_on:
            - php
        volumes:
            - ./public:/srv/public:ro
        ports:
            - 8000:80
        networks:
            - internal

networks:
    internal:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.100.0/28
