controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /api/{version}
    requirements:
        version: v\d+

kernel:
    resource: ../../src/Kernel.php
    type: annotation
